apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernetes-dashboard-tls
  namespace: kubernetes-dashboard
spec:
  secretName: kubernetes-dashboard-tls
  dnsNames:
    - k8s-dashboard-zmn0zjiwmju.dev.fctf.cloud
  issuerRef:
    name: letsencrypt-dev
    kind: ClusterIssuer