apiVersion: v1
kind: Secret
metadata:
  name: admin-mvc-secret
  namespace: app
stringData:
  DATABASE_URL: "mysql+pymysql://ctfd-username:Y3RmZC1wYXNzd29yZEA@mariadb-headless.db.svc.cluster.local:3306/ctfd"
  REDIS_URL: "redis://:Fctf2025@@redis-headless.db.svc.cluster.local:6379/0"
  REDIS_PASS: "Fctf2025@"
