FROM alpine:3.20

ENV KUBECTL_VERSION=v1.34.0

RUN apk add --no-cache curl bash ca-certificates git gettext \
    &&  curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" \
    && chmod +x kubectl \
    && mv kubectl /usr/local/bin/ \
    && kubectl version --client