apiVersion: v1
kind: Namespace
metadata:
  name: ${CHALLENGE_NAME}
  labels:
    ctf/temporary: "${IS_TEMPORARY}"
    ctf/expireAfter: "${CHALLENGE_TIMEOUT}"
    ctf/kind: "challenge"
---
apiVersion: v1
kind: Service
metadata:
  namespace: ${CHALLENGE_NAME}
  name: ${CHALLENGE_NAME}-svc
  labels:
    ctf/kind: "challenge"
spec:
  type: NodePort
  selector:
    app: ${CHALLENGE_NAME}
  ports:
    - name: tcp-challenge-nodeport
      protocol: TCP
      port: 3333
      targetPort: ${CONTAINER_PORT}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${CHALLENGE_NAME}-job
  namespace: ${CHALLENGE_NAME}
spec:
  ttlSecondsAfterFinished: ${CHALLENGE_TIMEOUT}
  template:
    metadata:
      labels:
        app: ${CHALLENGE_NAME}
        ctf/kind: "challenge"
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false # 🚫 Không gắn token API server
      containers:
        - name: challenge
          image: "${CONTAINER_IMAGE}"
          ports:
            - containerPort: ${CONTAINER_PORT}
          securityContext:
            allowPrivilegeEscalation: false # 🚫 Không cho escalate privilege
            privileged: false
            # runAsNonRoot: true # 🚫 Không chạy root
            # runAsUser: 1000
            # readOnlyRootFilesystem: false # (nếu muốn readonly thì chỉnh lại thành true)
            capabilities:
              drop: ["ALL"] # 🚫 Bỏ mọi Linux capabilities
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
              cpu: "${CPU_LIMIT}"
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: global-regcred
