apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
  namespace: challenge
spec:
  type: NodePort
  selector:
    app: ${APP_NAME}
  ports:
    - protocol: TCP
      port: ${SERVICE_PORT}
      targetPort: ${CONTAINER_PORT}
      nodePort: ${NODE_PORT}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${APP_NAME}-challenge-job
  namespace: challenge
  annotations:
    ttl-seconds-after-finished: "60"
spec:
  ttlSecondsAfterFinished: 60
  activeDeadlineSeconds: 900
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      restartPolicy: Never
      containers:
        - name: ${APP_NAME}
          image: ${CONTAINER_IMAGE}
          ports:
            - containerPort: ${CONTAINER_PORT}
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
              cpu: "${CPU_LIMIT}"
            requests:
              cpu: "${CPU_REQUEST}"
              memory: "${MEMORY_REQUEST}"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
  namespace: challenge
  annotations:
    ttl-seconds-after-finished: "60"
spec:
  type: NodePort
  selector:
    app: ${APP_NAME}
  ports:
    - protocol: TCP
      port: ${SERVICE_PORT}
      targetPort: ${CONTAINER_PORT}
      nodePort: ${NODE_PORT}
