apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitoring
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana-zmn0zjiwmju.fctf.cloud
  issuerRef:
    name: letsencrypt-dev
    kind: ClusterIssuer